services:
  mysql:
    container_name: virtual_drivers_mysql
    image: mysql:8
    ports:
      - '3308:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: virtual_drivers
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - virtual_drivers
  redis:
    container_name: virtual_drivers_redis
    image: redis:latest
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 3s
      retries: 60
    networks:
      - virtual_drivers

networks:
  virtual_drivers:
    name: virtual_drivers
    driver: bridge
