spring.config.activate.on-profile: dev
---
spring.config.activate.on-profile: prod
server:
  servlet:
    context-path: /api

spring:
  config:
    import:
      - persistence.yaml
      - api-client.yaml
      - cache.yaml

springdoc:
  swagger-ui:
    path: /docs
