spring.config.activate.on-profile: local, default
server:
  port: 8081
  servlet:
    context-path: /api

spring:
  config:
    import:
      - persistence-local.yaml
      - cache-local.yaml

---
spring.config.activate.on-profile: prod
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config:
    import:
      - persistence.yaml
      - cache.yaml
