name: ci-cd-server

on:
  push:
    branches:
      - cicd

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          DISDONG_USERNAME: ${{ secrets.DISDONG_USERNAME }}
          DISDONG_TOKEN: ${{ secrets.DISDONG_TOKEN }}
        run: ./gradlew clean build -x test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/virtual-drivers-server:${{ env.IMAGE_TAG }}
          context: ./virtual-drivers-server
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          key: ${{ secrets.AWS_EC2_PEM }}
          username: ubuntu
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker image prune -af
            docker pull ${{ secrets.DOCKERHUB_USER }}/virtual-drivers-server:${{ env.IMAGE_TAG }}

            rm -f server.sh
            touch server.sh

            echo "docker kill virtual-drivers-server 2>/dev/null" >> server.sh
            echo "docker rm virtual-drivers-server 2>/dev/null" >> server.sh
            echo docker run --name virtual-drivers-server --rm -d -p 80:8080 \
              --log-driver=syslog \
              ${{ secrets.DOCKERHUB_USER }}/virtual-drivers-server:${{ env.IMAGE_TAG }} >> server.sh

            bash server.sh
