### success case
GET http://localhost:8080/api/driving-direction?startLongitude=126.9918&startLatitude=37.5519&goalLongitude=126.7052&goalLatitude=37.4563

### failure case
GET http://localhost:8080/api/driving-direction?startLatitude=127.001&startLongitude=37.001&goalLatitude=127.001&goalLongitude=37.001